packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Auth
  "@auth/core": 0.41.2
  "@auth/drizzle-adapter": ~1.11.1
  "next-auth": 5.0.0-beta.31

  # Dev tooling
  eslint: ^10.2.1
  prettier: ^3.8.3
  tailwindcss: ^3.4.15
  typescript: ^6.0.3

  # Misc
  zod: ^4.3.6

  # AI
  ai: ^6.0.168
  "@ai-sdk/amazon-bedrock": ^4.0.96
  "@ai-sdk/anthropic": ^3.0.71
  "@ai-sdk/deepseek": ^2.0.29
  "@ai-sdk/google": ^3.0.64
  "@ai-sdk/groq": ^3.0.35
  "@ai-sdk/mistral": ^3.0.30
  "@ai-sdk/openai": ^3.0.53
  "@ai-sdk/react": ^3.0.170

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.67.1
  "@trpc/client": ^11.0.0-rc.824
  "@trpc/tanstack-react-query": ^11.0.0-rc.824
  "@trpc/server": ^11.0.0-rc.824

catalogs:
  react19:
    react: 19.0.1
    react-dom: 19.0.1
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.1
    "@types/react-dom": ^18.3.1
