import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import postcss from 'esbuild-postcss';
import { execFileSync } from "node:child_process";
import { dirname } from "path";
import { fileURLToPath } from "url";
const __pluginDir = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const isGithubAction = process.env.GITHUB_ACTIONS === "true";

// Determine output directory based on environment
const outdir = isGithubAction ? "dist" : "../..";

const rustTreeSitterBridgePlugin = {
	name: "rust-tree-sitter-bridge-build",
	setup(build) {
		build.onStart(() => {
			execFileSync("node", ["scripts/build-rust-tree-sitter-bridge.mjs"], {
				cwd: __pluginDir,
				env: process.env,
				stdio: "inherit",
			});
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: {
		main: "index.ts",
		styles: "styles.css",
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"sharp",
		...builtins,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	platform: "node",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: outdir,
	plugins: [
		postcss({
			plugins: {
				tailwindcss: {},
				autoprefixer: {},
			},
			inject: false,
			extract: true,
		}),
		rustTreeSitterBridgePlugin,
	],
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
		'process.env.GITHUB_ACTIONS': JSON.stringify(process.env.GITHUB_ACTIONS || "false"),
	},
	loader: {
		'.ts': 'ts',
		'.wasm': 'binary',
	},
	tsconfig: "tsconfig.json",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
